#!/bin/bash
#
# Create symlinks for setup files.

set -e
shopt -s extglob

die() {
  echo "Error: $1" >&2
  exit 1
}

#symlink() {
#  SRC="$1"
#  DEST="$2"
#  if [ -e "$DEST" ] && [ ! -L "$DEST" ]; then
#    die "file exists: $DEST"
#  fi
#
#  echo "deploying: $DEST"
#  rm -f "$DEST"
#  ln -s "$SRC" "$DEST"
#}
#

# use a real overwrite
overwrite() {
  SRC="$1"
  DEST="$2"
  if [ -e "$DEST" ]; then
    echo "Warning! File exists: $DEST"
  fi

  echo "deploying: $DEST"
  rm -f "$DEST"
  cp "$SRC" "$DEST"
}

[ -d .git ] || die "should run from git root"

REPOS_PATH="$PWD"

# bin scripts
#
scripts=`ls bin/`
mkdir -p ~/bin
cd ~/bin
for file in $scripts; do
  overwrite "$REPOS_PATH/bin/$file" "${file%.*}"
done


# dotfiles
#
cd $REPOS_PATH/dot
find . -type f | sed 's/^..//' | while read path; do
  dir=`sed -n '/\//s|/[^/]*$||p' <<< $path`  # (empty if at pwd)
  file=`basename $path`

  if [ "$dir" ]; then
    mkdir -p ~/.$dir
    cd ~/.$dir
  else
    file=".$file"
    cd ~
  fi

  overwrite "$REPOS_PATH/dot/$path" "$file"
done

# crons
#
if [ "$1" = "do-cron" ]; then
  cd $REPOS_PATH/cron
  for file in *; do
    fields=`grep '^# cron:' $file | sed 's/.*cron: //'`
    [ "$fields" = "no-auto-deploy" ] && continue

    line="$fields $REPOS_PATH/cron/$file"
    if crontab -l | grep -q "$file"; then
      echo "updating cron: $file"
      crontab -l | sed "/$file/s|.*|$line|" | crontab -
    else
      echo "adding cron: $file"
      ( crontab -l ; echo "$line" ) | crontab -
    fi
  done
fi

