xrdb .Xresources

/usr/bin/wicd-curses &
DEFAULT_SESSION=awesome
case $1 in
  awesome) exec ck-launch-session awesome ;;
  wmii) exec wmii ;;
  xmonad) exec xmonad ;;
  *) exec $DEFAULT_SESSION ;;
esac
